name: brilfit-ai
region: fra
services:
  - name: brilfit-ai
    git:
      repo_clone_url: https://github.com/AndreHolmanNetherlands/brilfit-ai.git
      branch: main
    run_command: streamlit run brilfit_ai.py --server.port=$PORT --server.address=0.0.0.0
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-1gb
    http_port: 8080
    routes:
      - path: /
